name: Deploy Python Bot to Railway
on:
  push:
    branches: [main]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Deploy to Railway
        uses: railwayapp/action@v1.3.0
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
